'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stateName={open:'开启中',merged:'已合入',closed:'已关闭未合入'},resultName={success:'成功',failure:'失败',running:'执行中',incomplete:'数据不完整'},kindName={create:'创建 PR',push:'推送提交',retest:'重跑请求',unknown:'请求未关联',note:'评论触发',merge_request:'PR 事件'},taskName={x86:'x86 构建',arm:'ARM 构建',dt:'DT 测试','pre-commit':'pre-commit','issue-check':'Issue 关联',other:'其他子任务'};
let snapshot,filtered=[],page=1,view='repositories',detailPR=null,repositoryIndex=null,repositorySnapshots={},currentRepository='ubs-engine';const PAGE_SIZE=15;
function num(n,d=2){return n==null?'—':Number(n).toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d});}
function minute(ms){return ms!=null&&ms>0&&ms<600?'<0.01':num(ms==null?null:ms/60000);}
function exact(ms){if(ms==null)return '—';return ms<1000?num(ms,0)+' ms':num(ms/1000,3)+' s';}
function date(ms,short=false){if(!ms)return '—';return new Date(ms).toLocaleString('sv-SE',{timeZone:'Asia/Shanghai',...(short?{year:'numeric',month:'2-digit',day:'2-digit'}:{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})});}
function link(url,label){let safe='';try{const u=new URL(url);if(u.protocol==='https:'&&['gitcode.com','ci.openeuler.openatom.cn'].includes(u.hostname))safe=u.href}catch{}return safe?`<a href="${esc(safe)}" target="_blank" rel="noreferrer">${label} <svg class="icon icon-sm" aria-hidden="true"><use href="#i-external-link"/></svg></a>`:label;}
function pill(key,group=resultName){return `<span class="pill ${esc(key)}">${esc(group[key]||key)}</span>`;}
function counts(bs){return Object.fromEntries(Object.keys(resultName).map(k=>[k,bs.filter(b=>b.status===k).length]));}
function metricHTML(s){return `<div class="metric-value" title="平均 ${exact(s.mean)} / P90 ${exact(s.p90)}">${minute(s.mean)}<span>/ ${minute(s.p90)}</span></div><span class="sample">${s.n} 个有效 PR${s.n===1?' · 样本不足':''}</span>`;}
function resultHTML(bs){const c=counts(bs);const icons={success:'i-check',failure:'i-x',running:'i-clock',incomplete:'i-alert-triangle'};return `<div class="results">${Object.entries(c).filter(([,n])=>n).map(([s,n])=>`<span class="result-dot ${s}" title="${resultName[s]} ${n} 批"><svg class="icon icon-sm" aria-hidden="true"><use href="#${icons[s]}"/></svg>${n}</span>`).join('')||'—'}</div>`;}
function qualityRows(){const rows=[];for(const p of filtered){for(const reason of p.issues||[])rows.push([p.number,'PR',reason]);for(const b of p.batches){for(const reason of b.issues||[])rows.push([p.number,'#'+b.number,reason]);if(b.status==='running')rows.push([p.number,'#'+b.number,'仍在执行：排除主要耗时统计']);}}for(const e of snapshot.meta.errors||[])rows.push(['采集',e.source,e.reason]);return rows;}
function readFilters(){return {query:$('query').value,state:$('state').value,quality:$('qualityFilter').value};}
function render(){if(view==='repositories'){renderRepositories();return}if(!snapshot)return;filtered=Metrics.sortPRs(Metrics.filterPRs(snapshot.prs,readFilters()),$('sort').value);const metricCache=new Map(filtered.map(p=>[p.number,Metrics.metrics(p.batches)]));const bs=filtered.flatMap(p=>p.batches),s=Metrics.aggregate(filtered),c=counts(bs),done=c.success+c.failure,pc=Object.fromEntries(Object.keys(stateName).map(k=>[k,filtered.filter(p=>p.state===k).length]));
 const sample=z=>`${z.n} 个有效 PR 样本${z.n===1?' · 样本不足':''}`;
 $('kpis').innerHTML=kpiHTML(filtered);
 const pct=filtered.length?s.e2e.n/filtered.length*100:0;$('coverage').innerHTML=`<strong><svg class="icon icon-sm" aria-hidden="true"><use href="#i-target"/></svg> PR 有效覆盖 ${num(pct,1)}% (${s.e2e.n}/${filtered.length})</strong><span class="track"><i style="width:${pct}%"></i></span><span>辅助：全部批次结果 · 成功 ${c.success} · 失败 ${c.failure} · 执行中 ${c.running} · 不完整 ${c.incomplete}</span><button id="showQuality">查看缺失与排除 <svg class="icon icon-sm" aria-hidden="true"><use href="#i-arrow-right"/></svg></button>`;$('showQuality').onclick=()=>changeView('quality');
 drawTrend(filtered);drawTasks(s);renderTable(metricCache);renderQuality();$('qualityBadge').textContent=qualityRows().length;$('footerMeta').textContent=`${filtered.length} PR · ${bs.length} BATCHES · LOCAL SNAPSHOT`;
}
function drawTrend(prs){const groups={};for(const p of prs){const m=Metrics.metrics(p.batches);if(m.e2e_ms==null)continue;const d=date(p.created_ms,true);(groups[d]??=[]).push(m.e2e_ms)}const series=Object.keys(groups).sort().map(d=>({d,...Metrics.stats(groups[d])}));if(!series.length){$('trend').innerHTML='<div class="empty">没有可用于趋势的有效 E2E 样本</div>';return}const W=660,H=196,L=48,R=18,T=14,B=32,max=Math.max(...series.map(s=>s.p90/60000),.01)*1.15;const x=i=>L+(W-L-R)*(series.length===1?.5:i/(series.length-1)),y=v=>T+(H-T-B)*(1-v/60000/max);let svg='';for(let i=0;i<4;i++){const value=max*i/3,yy=y(value*60000);svg+=`<line class="grid-line" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/><text class="axis-text" x="${L-10}" y="${yy+3}" text-anchor="end">${num(value,1)}</text>`}const points=key=>series.map((s,i)=>`${x(i)},${y(s[key])}`).join(' ');svg+=`<polygon class="area-fill" points="${x(0)},${H-B} ${points('mean')} ${x(series.length-1)},${H-B}"/><line class="guide" id="trendGuide" x1="0" x2="0" y1="${T}" y2="${H-B}" visibility="hidden"/><polyline class="p90-line" points="${points('p90')}"/><polyline class="mean-line" points="${points('mean')}"/>`;series.forEach((s,i)=>{svg+=`<circle class="dot" cx="${x(i)}" cy="${y(s.mean)}" r="3"/>`});series.forEach((s,i)=>{if(i===series.length-1||(i%Math.max(1,Math.ceil(series.length/6))===0&&i<series.length-1-Math.ceil(series.length/12)))svg+=`<text class="axis-text" x="${x(i)}" y="${H-9}" text-anchor="middle">${s.d.slice(5)}</text>`});const step=series.length>1?(W-L-R)/(series.length-1):W;svg+=`<rect class="dot-hit" x="${Math.max(0,L-step/2)}" y="${T}" width="${W-R-L+step}" height="${H-T-B}"/><circle class="dot" id="trendHoverDot" r="4.5" visibility="hidden"/>`;$('trend').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="按 PR 创建日期统计的 E2E 平均与 P90 趋势">${svg}</svg><div class="chart-tip" hidden></div>`;const svgEl=$('trend').querySelector('svg'),tip=$('trend').querySelector('.chart-tip'),hoverDot=$('trendHoverDot'),guide=$('trendGuide');svgEl.addEventListener('mousemove',e=>{const r=svgEl.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*W;let i=Math.round((px-L)/step);i=Math.max(0,Math.min(series.length-1,i));const s=series[i],cx=x(i),cy=y(s.mean);hoverDot.setAttribute('cx',cx);hoverDot.setAttribute('cy',cy);hoverDot.setAttribute('visibility','visible');guide.setAttribute('x1',cx);guide.setAttribute('x2',cx);guide.setAttribute('visibility','visible');tip.hidden=false;tip.innerHTML=`${s.d}<br>平均 <b>${minute(s.mean)}</b> · P90 <b>${minute(s.p90)}</b> 分钟<br>n=${s.n}`;const box=$('trend').getBoundingClientRect(),wpx=cx/W*box.width;let left=wpx+12;if(left+160>box.width)left=wpx-172;tip.style.left=Math.max(0,left)+'px';tip.style.top=Math.max(8,cy/H*box.height-14)+'px'});svgEl.addEventListener('mouseleave',()=>{tip.hidden=true;hoverDot.setAttribute('visibility','hidden');guide.setAttribute('visibility','hidden')});}
function drawTasks(s){const field=$('chartMetric').value;const max=Math.max(...['x86','arm','dt'].map(k=>Math.max(s[k][field].p90||0,s[k][field].mean||0)),1)*1.15;$('taskChart').innerHTML=['x86','arm','dt'].map(k=>{const z=s[k][field];return `<div class="task-bar"><div class="task-bar-head"><span>${taskName[k]}</span><small>${minute(z.mean)} / ${minute(z.p90)} <span title="有效样本数">· n=${z.n}</span></small></div><div class="bar-track" title="平均 ${exact(z.mean)} / P90 ${exact(z.p90)}"><div class="bar-fill" style="width:${(z.mean||0)/max*100}%"></div>${z.p90!=null?`<i class="bar-tick" style="left:${z.p90/max*100}%"></i>`:''}</div></div>`}).join('');}
function renderTable(cache){const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));page=Math.min(page,pages);const rows=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),field=$('tableMetric').value;$('prCount').textContent=filtered.length;$('prRows').innerHTML=rows.map(p=>{const s=cache.get(p.number);return `<tr data-pr="${p.number}"><td><button class="pr-title" title="${esc(p.title)}"><b>#${p.number}</b>${esc(p.title)}</button><small class="pr-meta">${date(p.created_ms,true)} · ${esc(p.author)}${p.merged_ms?' · 合入 '+date(p.merged_ms,true):''}</small></td><td>${pill(p.state,stateName)}</td><td><span class="metric-value">${p.submission_count} <span>提交 / ${p.batches.length} 批次</span></span></td><td>${resultHTML(p.batches)}</td><td><div class="metric-value" title="${s.representative_batch_number!=null?'Trigger #'+s.representative_batch_number+' · ':''}${exact(s.e2e_ms)}">${minute(s.e2e_ms)}</div><small class="sample">${s.representative_batch_number!=null?'Trigger #'+s.representative_batch_number:'无有效批次'}</small></td>${['x86','arm','dt'].map(k=>`<td class="num"><div class="metric-value" title="${exact(s[k][field+'_ms'])}">${minute(s[k][field+'_ms'])}</div></td>`).join('')}<td><svg class="icon icon-sm" style="color:var(--text-3)" aria-hidden="true"><use href="#i-chevron-right"/></svg></td></tr>`}).join('')||'<tr><td colspan="9"><div class="empty">当前无匹配 PR，请调整筛选条件。</div></td></tr>';$('prRows').querySelectorAll('tr[data-pr]').forEach(r=>r.onclick=()=>openDetail(Number(r.dataset.pr)));$('pageInfo').textContent=`${page} / ${pages}`;$('prev').disabled=page<=1;$('next').disabled=page>=pages;const label={e2e:'代表 E2E 从长到短；相同 E2E 按创建时间从新到旧',batches:'批次数从多到少；相同批次数按创建时间从新到旧',created:'创建时间从新到旧'};$('rowInfo').textContent=`显示 ${filtered.length?(page-1)*PAGE_SIZE+1:0}–${Math.min(page*PAGE_SIZE,filtered.length)} / ${filtered.length} 条 · ${label[$('sort').value]}`;}
function renderQuality(){const rows=qualityRows();$('qualityContent').innerHTML=`<p class="quality-intro">当前筛选共有 ${rows.length} 条质量提示。无请求时间的批次仍可查看 Jenkins 耗时，但不进入 E2E 平均/P90。</p><div class="quality-list">${rows.map(r=>`<div class="quality-row"><a href="#" data-open="${esc(r[0])}">${typeof r[0]==='number'?'PR #':''}${esc(r[0])}</a><span>${esc(r[1])}</span><span class="reason">${esc(r[2])}</span></div>`).join('')||'<div class="empty">当前筛选无数据质量问题</div>'}</div>`;$('qualityContent').querySelectorAll('[data-open]').forEach(a=>a.onclick=e=>{e.preventDefault();if(Number(a.dataset.open))openDetail(Number(a.dataset.open))});}
function changeView(next){
 document.querySelectorAll('main > .export-notice').forEach(n=>n.remove());
 if(next==='overview'||next==='prs'){currentRepository='ubs-engine';next='single'}
 if(next.startsWith('repo/')){const parts=next.split('/');currentRepository=decodeURIComponent(parts[1]);next=['quality','method'].includes(parts[2])?parts[2]:'single'}
 if(!['repositories','single','quality','method'].includes(next))next='repositories';
 view=next;snapshot=repositorySnapshots[currentRepository]||null;page=1;
 for(const id of ['repositories','overview','prs','quality','method'])$(id).hidden=!(id===next||(next==='single'&&['overview','prs'].includes(id)));
 document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===next));
 const cross=next==='repositories';$('repositoryControls').hidden=cross;
 $('query').closest('label').hidden=cross;$('qualityFilter').closest('label').hidden=cross;
 $('repositorySelect').value=currentRepository;
 $('pageSubtitle').textContent=cross?'九仓 PR 工程效率 · 每个 PR 的最长有效 E2E 批次作为代表值':currentRepository+' 门禁效率 · 从提交请求到最后一个子任务结束';
 document.title=(cross?'九仓 PR 工程效率':currentRepository)+' · PR 工程效率';$('repositoryLink').href='https://gitcode.com/openeuler/'+encodeURIComponent(currentRepository);
 const entry=repositoryIndex?.repositories.find(r=>r.name===currentRepository);const m=cross?repositoryIndex:snapshot?.meta;
 $('range').textContent=m?date(m.start_ms,true)+' → '+date(m.end_ms,true):'未获取数据';$('range').title=m?date(m.start_ms)+' → '+date(m.end_ms):'';
 $('snapshotTime').textContent=cross?'各仓采集时间见下表':snapshot?'采集于 '+date(Date.parse(snapshot.meta.collected_at)):'';
 $('repositoryStatus').textContent=entry?repositoryState(entry,snapshot):'';
 $('notice').hidden=cross||(!entry?.error&&entry?.status==='success'&&snapshot?.meta.start_ms===repositoryIndex.start_ms&&snapshot?.meta.end_ms===repositoryIndex.end_ms);
 $('notice').textContent=entry?[repositoryState(entry,snapshot),entry.error].filter(Boolean).join(' · '):'未找到仓库';
 $('loading').hidden=cross||!!snapshot||next==='method';
 if(!cross&&!snapshot){$('loading').textContent='该仓库尚未获取数据，请查看采集状态后运行采集命令。';for(const id of ['overview','prs','quality'])$(id).hidden=true;$('qualityBadge').textContent='—';$('footerMeta').textContent=currentRepository+' · 未获取数据';}
 history.replaceState(null,'','#'+(cross?'repositories':'repo/'+encodeURIComponent(currentRepository)+(next==='single'?'':'/'+next)));
 render();
}
function repositoryState(entry,snap){if(!snap)return entry.status==='failed'?'未获取数据 · 采集失败':'未获取数据 · 待采集';const stale=snap.meta.start_ms!==repositoryIndex.start_ms||snap.meta.end_ms!==repositoryIndex.end_ms;if(stale)return '过期快照 · 不计跨仓汇总';return ({success:'采集完成',partial:'部分采集 · 需关注',failed:'采集失败 · 保留快照',pending:'待采集'})[entry.status]||entry.status;}
function kpiHTML(prs){const s=Metrics.aggregate(prs),pc=Object.fromEntries(Object.keys(stateName).map(k=>[k,prs.filter(p=>p.state===k).length])),pair=(label,z)=>`<article class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${minute(z.mean)}<em>平均</em></div><small>P90 ${minute(z.p90)} 分钟 · ${z.n} 个有效 PR</small></article>`;return `<article class="kpi kpi-dark"><div class="kpi-label">PR 数量</div><div class="kpi-value">${prs.length}<em>个</em></div><small>开启 ${pc.open} · 合入 ${pc.merged} · 关闭 ${pc.closed}</small></article>${pair('门禁 E2E',s.e2e)}${pair('x86 构建',s.x86.total)}${pair('ARM 构建',s.arm.total)}${pair('DT 测试',s.dt.total)}`;}
function crossRows(){return Metrics.repositoryRows(repositoryIndex,repositorySnapshots,$('state').value).sort((a,b)=>$('repositorySort').value==='prs'?b.prs.length-a.prs.length:$('repositorySort').value==='name'?a.name.localeCompare(b.name):(b.metrics.e2e.p90??-1)-(a.metrics.e2e.p90??-1));}
function maxE2E(prs){const p=Metrics.sortPRs(prs,'e2e')[0],m=p&&Metrics.metrics(p.batches);return {p,m};}
function renderAttention(prs,rows){const failures=prs.reduce((n,p)=>n+p.batches.filter(b=>b.status==='failure').length,0),quality=prs.filter(p=>!Metrics.metrics(p.batches).e2e_ms||(p.issues||[]).length||p.batches.some(b=>b.status==='incomplete'||(b.issues||[]).length)).length,slow=maxE2E(prs),partial=rows.filter(r=>r.status==='partial').length;$('attention').innerHTML=`<div class="attention-head"><div><div class="eyebrow">Action center</div><h2>当前效率概览</h2><p>按可核对的实际耗时、执行次数和批次结果展示。</p></div><span class="snapshot-health">${partial?`注意：${partial} 个仓库部分采集，指标可能低估`:`采集于 ${date(Date.parse(repositoryIndex.generated_at))}`}</span></div><div class="attention-cards"><div class="attention-card"><strong>${prs.length}</strong><span>纳入统计的 PR</span><small>当前筛选范围</small></div><div class="attention-card"><strong>${minute(slow.m?.e2e_ms)}</strong><span>最长代表 E2E</span><small>${slow.p?`${slow.p.number?`PR #${slow.p.number}`:''}`:'无有效样本'}</small></div><div class="attention-card"><strong>${failures}</strong><span>失败门禁批次</span><small>跨全部 PR 批次</small></div><div class="attention-card"><strong>${quality}</strong><span>数据质量问题</span><small>需单独核验</small></div></div>`;}
function renderExceptions(prs,repositoryRows){const repoFor=p=>(repositoryRows.find(r=>r.prs.includes(p))||{}).name||'未知仓库',rows=Metrics.sortPRs(prs,'e2e').filter(p=>Metrics.metrics(p.batches).e2e_ms!=null).slice(0,8);$('exceptionRows').innerHTML=rows.length?rows.map(p=>{const m=Metrics.metrics(p.batches),failed=p.batches.filter(b=>b.status==='failure').length,repo=repoFor(p);return `<button class="exception-row" data-repo="${esc(repo)}" data-exception="${p.number}"><span class="exception-repo">${esc(repo)}<small>#${p.number} · ${date(p.created_ms,true)}</small></span><span class="exception-title">${esc(p.title)}<small>${pill(p.state,stateName)}${failed?` · 失败批次 ${failed}`:''}</small></span><span class="exception-e2e">${minute(m.e2e_ms)}<small>E2E · Trigger #${m.representative_batch_number??'—'}</small></span><span class="exception-why">${p.submission_count} 次提交 · ${p.batches.length} 批门禁；点击查看全部批次与任务耗时。</span><svg class="icon icon-sm" aria-hidden="true"><use href="#i-chevron-right"/></svg></button>`}).join(''):'<div class="empty">当前没有可比较的 E2E 样本。</div>';$('exceptionRows').querySelectorAll('[data-exception]').forEach(el=>el.onclick=()=>{currentRepository=el.dataset.repo;changeView('repo/'+encodeURIComponent(currentRepository));setTimeout(()=>openDetail(Number(el.dataset.exception)),0);});}
function renderRepositories(){if(!repositoryIndex)return;const rows=crossRows(),prs=rows.flatMap(r=>r.prs),s=Metrics.aggregate(prs);renderAttention(prs,rows);renderExceptions(prs,rows);$('repositoryKpis').innerHTML=kpiHTML(prs);$('repositoryCoverage').textContent=`PR 有效覆盖 ${prs.length?num(s.e2e.n/prs.length*100,1):'0.0'}% (${s.e2e.n}/${prs.length}) · ${rows.filter(r=>r.included).length}/${rows.length} 仓纳入汇总`;$('repositoryRows').innerHTML=rows.map(r=>{const slow=maxE2E(r.prs);return `<tr><td><a href="#repo/${encodeURIComponent(r.name)}">${esc(r.name)} →</a><small>${esc(r.repository)}</small></td><td>${slow.m?`${minute(slow.m.e2e_ms)}<small>PR #${slow.p.number} · Trigger #${slow.m.representative_batch_number}</small>`:'—'}</td><td><strong>${r.included?r.prs.length:'—'}</strong><small>${r.included?`${r.counts.open} / ${r.counts.merged} / ${r.counts.closed}`:'未计入'}</small></td><td>${metricHTML(r.metrics.e2e)}</td>${['x86','arm','dt'].map(k=>`<td>${metricHTML(r.metrics[k].total)}</td>`).join('')}<td>${r.included?`${r.prs.length?num(r.metrics.e2e.n/r.prs.length*100,1):'0.0'}%<small>${repositoryState(r,repositorySnapshots[r.name])}</small>`:'—'}</td></tr>`}).join('');$('footerMeta').textContent=`${rows.length} REPOSITORIES · ${prs.length} PR · DAILY SNAPSHOT`;}
function exportRepositories(){const heads=['仓库','采集状态','纳入跨仓汇总','采集时间','PR数','开启','合入','关闭','有效代表PR数','覆盖率','E2E平均ms','E2EP90ms','E2E有效PR数'];for(const k of ['x86','ARM','DT'])heads.push(k+'总耗时平均ms',k+'总耗时P90ms',k+'有效PR数');const rows=crossRows().map(r=>{const a=[r.repository,repositoryState(r,repositorySnapshots[r.name]),r.included,repositorySnapshots[r.name]?.meta.collected_at,r.included?r.prs.length:null,...['open','merged','closed'].map(k=>r.included?r.counts[k]:null),r.metrics.e2e.n,r.included&&r.prs.length?r.metrics.e2e.n/r.prs.length:null,r.metrics.e2e.mean,r.metrics.e2e.p90,r.metrics.e2e.n];for(const k of ['x86','arm','dt'])a.push(r.metrics[k].total.mean,r.metrics[k].total.p90,r.metrics[k].total.n);return a});download([heads,...rows],'repositories-summary.csv');}
function batchHTML(b,expand){const all=[{...b.trigger,kind:'trigger'},...b.children],base=Math.min(...all.map(j=>j.scheduled_ms??j.start_ms).filter(Number.isFinite)),end=Math.max(...all.map(j=>j.end_ms??j.start_ms).filter(Number.isFinite)),span=Math.max(1,end-base);return `<details class="batch ${expand?'representative':''}" ${expand?'open':''}><summary><svg class="icon icon-sm chev" aria-hidden="true"><use href="#i-chevron-right"/></svg>${pill(b.status)}<strong>Trigger #${b.number}</strong><small>${b.cancelled?'已取消 · ':''}${expand?'用于 PR 效率汇总':b.eligible?'有效批次':'未纳入 E2E 统计'}</small><span class="batch-duration">E2E ${minute(b.e2e_ms)} min</span></summary><div class="batch-content"><div class="batch-context">请求：${date(b.request_ms)} → 全批结束：${date(b.end_ms)}<br>Jenkins 入队至全批结束：<b>${minute(b.jenkins_ms)} min</b> · ${link(b.url,'查看 trigger')}<br>${esc(b.association||'关联信息缺失')}${b.webhook_ms?' · webhook '+date(b.webhook_ms):''}</div><div class="timeline-head"><span>任务 / 构建</span><span>同批时间线（包含排队）</span><span style="text-align:right">排队 min</span><span style="text-align:right">执行 min</span><span style="text-align:right">总计 min</span><span>结果</span></div>${all.map(j=>{const start=j.start_ms??base,queue=j.queue_ms??0,dur=j.duration_ms??0,offset=(start-queue-base)/span*100;return `<div class="timeline-row"><span>${link(j.url,esc(j.kind==='trigger'?'Trigger':taskName[j.kind])+' #'+esc(j.number||b.number))}</span><div class="timeline-rail" title="排队 ${exact(j.queue_ms)} / 执行 ${exact(j.duration_ms)}"><span class="timeline-queue" style="left:${Math.max(0,offset)}%;width:${queue/span*100}%"></span><span class="timeline-exec ${j.result&&j.result!=='SUCCESS'?'failure':''}" style="left:${Math.max(0,(start-base)/span*100)}%;width:${dur/span*100}%"></span></div><span class="time-number" title="${exact(j.queue_ms)}">${minute(j.queue_ms)}</span><span class="time-number" title="${exact(j.duration_ms)}">${minute(j.duration_ms)}</span><span class="time-number" title="${exact(j.total_ms)}">${minute(j.total_ms)}</span><span>${pill(j.building?'running':j.result==='SUCCESS'?'success':j.result?'failure':'incomplete')}${j.result&&j.result!=='SUCCESS'?`<small> ${esc(j.result)}</small>`:''}</span></div>`}).join('')}<div class="timeline-legend"><i></i>排队 <i></i>执行 · 精确耗时见悬浮提示</div>${b.issues?.length?`<div class="batch-issues">${b.issues.map(esc).join('<br>')}</div>`:''}</div></details>`;}
function openDetail(n){detailPR=snapshot.prs.find(p=>p.number===n);if(!detailPR)return;const p=detailPR,s=Metrics.metrics(p.batches),groups=new Map();for(const b of p.batches){const key=b.event_id||'unmatched';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(b)}let first=true;const detailGroups=[...(p.events||[]).map(e=>({e,bs:groups.get(e.id)||[]})),...(groups.has('unmatched')?[{e:{kind:'unknown'},bs:groups.get('unmatched')}]:[])];$('detailBody').innerHTML=`<div class="detail-title"><h2>${link(p.url,'#'+p.number)} ${esc(p.title)}</h2>${pill(p.state,stateName)}</div><div class="detail-meta">${esc(p.author)} · 创建 ${date(p.created_ms)} · 合入 ${date(p.merged_ms)} · 关闭 ${date(p.closed_ms)}<br>${p.submission_count} 次提交事件 · 全部 ${p.batches.length} 批门禁 · head ${esc(p.head_sha||'未知')}</div>${detailGroups.map(({e,bs})=>`<section class="event-group"><div class="event-heading"><strong>${esc(kindName[e.kind]||e.kind)}</strong><span>${date(e.time_ms)}</span><code>${esc(e.sha||(e.shas?.length?e.shas.join(' · '):'SHA 未确认'))}</code><span>${bs.length} 批</span></div>${bs.map(b=>{return batchHTML(b,b.url===s.representative_batch_url)}).join('')||`<div class="batch-context">此事件未关联到 trigger，详见数据质量提示</div>`}</section>`).join('')}${p.issues?.length?`<div class="batch-issues">${p.issues.map(esc).join('<br>')}</div>`:''}`;if(!$('detail').open)$('detail').showModal();}
async function download(rows,name){
 const parent=$('detail').open?$('detailBody'):document.querySelector('main');let notice=parent.querySelector('.export-notice');
 if(!notice){notice=document.createElement('div');notice.className='export-notice';notice.setAttribute('role','status');parent.prepend(notice)}
 notice.textContent='正在保存 CSV…';
 try{const file=await Metrics.saveCsv(rows,name);notice.innerHTML=file.mode==='saved'?'已保存到本地：<a href="'+esc(file.url)+'" download="'+esc(file.name)+'">'+esc(file.name)+' ↓</a>':'已下载：'+esc(file.name);}
 catch(e){notice.textContent='导出失败：'+e.message;}
}
function exportPRs(){const heads=['仓库','PR','标题','状态','作者','创建时间','合入时间','提交次数','全部批次数','代表trigger编号','代表trigger链接','E2E ms'];for(const k of ['x86','ARM','DT'])for(const f of ['排队','执行','总计'])heads.push(`${k}${f}ms`);const rows=filtered.map(p=>{const s=Metrics.metrics(p.batches),r=[snapshot.meta.repository,p.number,p.title,stateName[p.state],p.author,date(p.created_ms),date(p.merged_ms),p.submission_count,p.batches.length,s.representative_batch_number,s.representative_batch_url,s.e2e_ms];for(const k of ['x86','arm','dt'])for(const f of ['queue','duration','total'])r.push(s[k][f+'_ms']);return r});download([heads,...rows],currentRepository+'-pr-summary.csv');}
function exportBatches(){if(!detailPR)return;const rows=[['仓库','PR','trigger','E2E结果','触发类型','SHA','请求时间','E2E ms','Jenkins ms','有效E2E批次','用于PR效率汇总','子任务','子任务结果','排队ms','执行ms','总计ms','数据问题']];for(const b of detailPR.batches){for(const j of b.children.length?b.children:[{}])rows.push([snapshot.meta.repository,detailPR.number,b.url,resultName[b.status],kindName[b.event_type]||b.event_type,b.sha,date(b.request_ms),b.e2e_ms,b.jenkins_ms,b.eligible,b.url===Metrics.metrics(detailPR.batches).representative_batch_url,j.url,j.result,j.queue_ms,j.duration_ms,j.total_ms,(b.issues||[]).join('; ')])}download(rows,`${currentRepository}-pr-${detailPR.number}-batches.csv`);}
async function load(){try{$('loading').hidden=true;const skel=n=>Array.from({length:n},()=>`<div class="skel skel-card"></div>`).join(''),skelRows=(n,c)=>Array.from({length:n},()=>`<tr><td colspan="${c}"><div class="skel skel-row"></div></td></tr>`).join('');$('kpis').innerHTML=skel(5);$('repositoryKpis').innerHTML=skel(5);$('prRows').innerHTML=skelRows(5,9);$('repositoryRows').innerHTML=skelRows(5,8);const response=await fetch('data/repositories.json',{cache:'no-store'});if(!response.ok)throw Error('仓库索引 HTTP '+response.status);const index=await response.json();if(!Array.isArray(index.repositories))throw Error('仓库索引格式无效');const snapshots={};await Promise.all(index.repositories.map(async entry=>{if(!entry.snapshot)return;try{const r=await fetch('data/'+entry.snapshot,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();if(!data.meta||!Array.isArray(data.prs)||data.meta.repository!==entry.repository)throw Error('仓库快照格式或归属不匹配');snapshots[entry.name]=data}catch(error){entry.status='failed';entry.error='快照读取失败：'+error.message}}));repositoryIndex=index;repositorySnapshots=snapshots;$('repositorySelect').innerHTML=index.repositories.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('');$('loading').hidden=true;changeView(location.hash.slice(1)||'repositories')}catch(e){$('loading').hidden=false;$('loading').textContent='无法读取看板：'+e.message+'。请运行 python collect.py --all 并通过本地服务打开。';for(const id of ['repositories','overview','prs','quality','method'])$(id).hidden=true;}}
for(const id of ['query','state','qualityFilter'])$(id).addEventListener(id==='query'?'input':'change',()=>{page=1;render()});for(const id of ['sort','tableMetric','chartMetric'])$(id).onchange=()=>{page=1;render()};$('reset').onclick=()=>{for(const id of ['query','state','qualityFilter'])$(id).value='';page=1;render()};$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};$('export').onclick=exportPRs;$('exportBatches').onclick=exportBatches;$('exportQuality').onclick=()=>download([['仓库','PR','批次','原因'],...qualityRows().map(r=>[snapshot.meta.repository,...r])],currentRepository+'-quality.csv');$('closeDetail').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close()}});document.querySelectorAll('[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();changeView(a.dataset.view)});$('reload').onclick=load;$('repositorySelect').onchange=()=>changeView('repo/'+encodeURIComponent($('repositorySelect').value));$('backRepositories').onclick=()=>changeView('repositories');$('repositorySort').onchange=renderRepositories;$('exportRepositories').onclick=exportRepositories;window.addEventListener('hashchange',()=>changeView(location.hash.slice(1)||'repositories'));load();
